/* ============================================================================
   Unified catalogue sync
   ----------------------------------------------------------------------------
   data/leboncoin.json + data/vinted.json + data/manual.json
     → merge, dedupe cross-postings, timestamp
     → data/catalog.json           (canonical machine-readable catalogue)
     → assets/products.js          (window.CP_PRODUCTS, loaded by boutique.html)

   Cross-posting dedupe: the same piece listed on both platforms usually keeps
   the same title and price, so items sharing (folded title + price) collapse
   into one card. Priority manual > vinted > leboncoin (Vinted is the shop the
   site's CTAs favour); the losing listing's link is kept in `also_on`.

   Timestamps are preserved from the previous catalog.json whenever an item's
   content is unchanged, so re-running the sync produces no git noise.
   ========================================================================== */
import fs from 'node:fs';
import path from 'node:path';
import {
  DATA_DIR, ROOT, fingerprint, fold, normalizeItem, readJsonIfExists, readManualFile, writeJson
} from './lib/normalize.js';

const CATALOG_FILE = path.join(DATA_DIR, 'catalog.json');
const PRODUCTS_JS = path.join(ROOT, 'assets', 'products.js');

/* Merge priority: Sanity (the CMS) wins, then hand-curated, then platform imports.
   The Sanity entry is a no-op until scripts/fetch-sanity.js has written data/sanity.json. */
const SOURCES = [
  { source: 'sanity', load: () => { const f = path.join(DATA_DIR, 'sanity.json'); return fs.existsSync(f) ? readManualFile(f).items.map((r) => normalizeItem(r, 'sanity')).filter(Boolean) : null; } },
  { source: 'manual', load: () => readManualFile(path.join(DATA_DIR, 'manual.json')).items.map((r) => normalizeItem(r, 'manual')).filter(Boolean) },
  { source: 'vinted', load: () => (readJsonIfExists(path.join(DATA_DIR, 'vinted.json'))?.items) ?? null },
  { source: 'leboncoin', load: () => (readJsonIfExists(path.join(DATA_DIR, 'leboncoin.json'))?.items) ?? null }
];

function main() {
  const merged = [];
  const byDedupeKey = new Map();
  const byId = new Map();

  for (const { source, load } of SOURCES) {
    let items;
    try {
      items = load();
    } catch (e) {
      console.error(`  ! ${source}: ${e.message} — treating as empty`);
      items = [];
    }
    if (items == null) {
      console.log(`  ${source}: no normalized data yet (run npm run import:${source}) — skipping`);
      continue;
    }
    for (const item of items) {
      if (byId.has(item.id)) {
        console.warn(`  ! duplicate id "${item.id}" — keeping the ${byId.get(item.id).source} entry`);
        continue;
      }
      const key = `${fold(item.title_fr)}|${item.price ?? ''}`;
      const existing = byDedupeKey.get(key);
      if (existing) {
        // Same piece cross-posted on another platform: keep one card, both links.
        existing.also_on = [...(existing.also_on || []), { source: item.source, url: item.source_url }];
        console.log(`  ~ "${item.title_fr}" (${item.source}) merged into ${existing.source} listing`);
        continue;
      }
      byId.set(item.id, item);
      byDedupeKey.set(key, item);
      merged.push(item);
    }
    console.log(`  ${source}: ${items.length} listing(s)`);
  }

  // Keep created_at/updated_at stable for unchanged items (git-friendly).
  const previous = new Map((readJsonIfExists(CATALOG_FILE)?.items || []).map((i) => [i.id, i]));
  const now = new Date().toISOString().slice(0, 10);
  for (const item of merged) {
    const prev = previous.get(item.id);
    const unchanged = prev && fingerprint(prev) === fingerprint(item);
    item.created_at = item.created_at || prev?.created_at || now;
    item.updated_at = unchanged ? prev.updated_at : (item.updated_at || now);
  }

  merged.sort((a, b) => (b.created_at || '').localeCompare(a.created_at || '') || a.id.localeCompare(b.id));

  writeJson(CATALOG_FILE, { count: merged.length, items: merged });

  const banner =
    '/* AUTO-GENERATED by scripts/sync-catalog.js — DO NOT EDIT.\n' +
    '   Edit data/*-manual.json (or data/manual.json), then run `npm run sync:catalog`.\n' +
    '   Canonical data: data/catalog.json */\n';
  const js = `${banner}window.CP_PRODUCTS = ${JSON.stringify(merged, null, 2)};\n`;
  fs.writeFileSync(PRODUCTS_JS, js, 'utf8');

  console.log(`catalog: ${merged.length} item(s) → data/catalog.json + assets/products.js`);

  // CMS content (homepage/impact/FAQ/settings from Sanity) → assets/content.js (window.CP_CONTENT).
  const CONTENT_JSON = path.join(DATA_DIR, 'content.json');
  if (fs.existsSync(CONTENT_JSON)) {
    const content = readJsonIfExists(CONTENT_JSON) || {};
    const contentBanner =
      '/* AUTO-GENERATED from Sanity by scripts/fetch-sanity.js — DO NOT EDIT.\n' +
      '   Source of truth: the CosyPrints Studio (cosyprints.sanity.studio). */\n';
    fs.writeFileSync(
      path.join(ROOT, 'assets', 'content.js'),
      `${contentBanner}window.CP_CONTENT = ${JSON.stringify(content, null, 2)};\n`,
      'utf8',
    );
    console.log('content: assets/content.js written');
  }
}

main();
